### ISSUE TITLE
Audio solution proven to work?

### ISSUE THREAD

**Issue by skbolton** [BNieuwenhuizen/zenbook-s16#10]
I have tried the audio solution presented in the readme and I am not seeing any results. Toggling the output in pwvucontrol from the proposed upmix sink to the built in controller sounds the exact same. I have also been able to go into advanced mode and control the rear channels individually and adjusting their volume doesn't make a difference. It really is as if the front speakers are the only ones being used.

I was hoping that someone who had used the fix can confirm that it really does work by toggling back to the builtin and confirming that a change happens. Or that adjusting the rear channels does anything for them
![image](https://github.com/user-attachments/assets/71b72a0e-c9ec-4afc-bca6-73afdb693878)

**Comment by skbolton** [comment]
I feel like I can get plenty of volume but it is still very high frequency in tambre. I installed windows last night on the laptop again just to get a feel for what the audio could be. It was surprisingly bassy and loud. I can tell on the linux side something is up.

**Comment by Shyrogan** [comment]
Hi, there should be a "Stereo to 4.0 upmix" output if you follow this guide configuration I believe.

**Comment by gungun974** [comment]
> I have tried the audio solution presented in the readme and I am not seeing any results. Toggling the output in pwvucontrol from the proposed upmix sink to the built in controller sounds the exact same. I have also been able to go into advanced mode and control the rear channels individually and adjusting their volume doesn't make a difference. It really is as if the front speakers are the only ones being used.
> 
> I was hoping that someone who had used the fix can confirm that it really does work by toggling back to the builtin and confirming that a change happens. Or that adjusting the rear channels does anything for them ![image](https://private-user-images.githubusercontent.com/13260877/383764682-71b72a0e-c9ec-4afc-bca6-73afdb693878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDYzNjAsIm5iZiI6MTczMTA0NjA2MCwicGF0aCI6Ii8xMzI2MDg3Ny8zODM3NjQ2ODItNzFiNzJhMGUtYzllYy00YWZjLWJjYTYtNzNhZmRiNjkzODc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA2MDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMmFiMDRkYWJkNjI0MmIxMjM0NjM5YTFkMTQxYTY4MjRlM2RiZjZiNmVlZmRjMjcxNTU3MjZlYzY4NDM4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1pG0ViIichTw7k6PdjjpnLaYqxFNmeUar6OCebUwS2I)

Your pages should look like this :

![image](https://github.com/user-attachments/assets/a76927dd-b9e4-4889-a2a2-049b06cf98b0)

![image](https://github.com/user-attachments/assets/ebafb53e-84a1-4cad-9ae1-167c499eab1a)

**Comment by IShashkin** [comment]
I'm on Fedora 41 and am trying to fix the issue with audio. Unfortunately it doesn't work for me. `alsa_output.pci-0000_c4_00.6.analog-surround-40` device is mentioned in the fix. I don't see it in the list of audio devices
```
vasia@fedora:~$ LANG=C pactl list | grep -A2 'Source #' | grep 'Name: ' | cut -d" " -f2
alsa_output.pci-0000_c4_00.6.HiFi__Speaker__sink.monitor
alsa_input.pci-0000_c4_00.6.HiFi__Mic2__source
alsa_input.pci-0000_c4_00.6.HiFi__Mic1__source
```
Could someone with working audio post an output of this command?

**Comment by fallingcats** [comment]
> I'm on Fedora 41 and am trying to fix the issue with audio. Unfortunately it doesn't work for me. `alsa_output.pci-0000_c4_00.6.analog-surround-40` device is mentioned in the fix. I don't see it in the list of audio devices
> 
> ```
> vasia@fedora:~$ LANG=C pactl list | grep -A2 'Source #' | grep 'Name: ' | cut -d" " -f2
> alsa_output.pci-0000_c4_00.6.HiFi__Speaker__sink.monitor
> alsa_input.pci-0000_c4_00.6.HiFi__Mic2__source
> alsa_input.pci-0000_c4_00.6.HiFi__Mic1__source
> ```
> 
> Could someone with working audio post an output of this command?

I'm on arch and it works for me:
```
alsa_output.pci-0000_c4_00.6.analog-surround-40.monitor
alsa_input.pci-0000_c4_00.6.analog-stereo
sink.upmix_4_0.monitor
```

**Comment by IShashkin** [comment]
@fallingcats What kernel version do you use?

**Comment by fallingcats** [comment]
> @fallingcats What kernel version do you use?

Currently 6.12 but afaik it has always worked, even on 6.10

**Comment by smithfred** [comment]
On Fedora 41 here (I'm the creator of the original workaround ;)) - something seems to have broken this recently, seeing the same issue as @fallingcats now too.

**Comment by ThatOneCalculator** [comment]
Same here

**Comment by fallingcats** [comment]
> On Fedora 41 here (I'm the creator of the original workaround ;)) - something seems to have broken this recently, seeing the same issue as @fallingcats now too.

It's working fine for me, but I always need to set the default sink again after disconnecting my bluetooth headphones.

**Comment by smithfred** [comment]
Looks like Alsa 1.2.13 broke things - downgrading to 1.2.12 restored the previous behaviour where the woofers are exposed as 4.0 rear channels, vs. being absent entirely with 1.2.13.

To downgrade:

```sh
sudo dnf install https://kojipkgs.fedoraproject.org//packages/alsa-lib/1.2.12/2.fc41/x86_64/alsa-lib-1.2.12-2.fc41.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/alsa-lib/1.2.12/2.fc41/noarch/alsa-ucm-1.2.12-2.fc41.noarch.rpm https://kojipkgs.fedoraproject.org//packages/alsa-utils/1.2.12/2.fc41/x86_64/alsa-utils-1.2.12-2.fc41.x86_64.rpm
```

After a reboot, the workaround should work again.

**Comment by ThatOneCalculator** [comment]
I'm still on alsa 1.2.12 for all the main packages, but still experience this.]

```
$  yay -Q | grep "alsa"

alsa-card-profiles 1:1.2.6-1.1
alsa-firmware 1.2.4-4
alsa-lib 1.2.12-1.1
alsa-plugins 1:1.2.12-4.1
alsa-topology-conf 1.2.5.1-4
alsa-ucm-conf 1.2.12-1
alsa-utils 1.2.12-1.1
lib32-alsa-lib 1.2.12-1
lib32-alsa-plugins 1.2.12-1
pipewire-alsa 1:1.2.6-1.1
qemu-audio-alsa 9.1.1-2
```

**Comment by ThatOneCalculator** [comment]
Added to the Arch Wiki: https://wiki.archlinux.org/title/ASUS_Zenbook_UM5606#Audio

**Comment by perexg** [comment]
Pls, create an issue in https://github.com/alsa-project/alsa-ucm-conf/issues to resolve this issue in upstream. Attach also output from `alsa-info.sh --no-upload` .

**Comment by IShashkin** [comment]
@perexg Here we go https://github.com/alsa-project/alsa-ucm-conf/issues/467

**Comment by ThatOneCalculator** [comment]
This issue should be closed now

**Comment by skbolton** [comment]
I'll go ahead and close this. The previous solution never worked for me, but I just rebuilt nixos with the new 6.13-rc2 kernel and now sound is working! These really are great speakers now with everything working.
