### ISSUE TITLE
Keyboard backlight tracking issue

### ISSUE THREAD

**Issue by clemej** [BNieuwenhuizen/zenbook-s16#5]
Thanks for putting these notes up.  Thought it'd make sense to create an issue to track keyboard backlight control. 

My keyboard backlight just pulses continuously, and has since the moment I turned on the machine the first time out of the box. It never responded to keyboard shortcuts in the bios, windows, or linux.  It's just permanently pulsing.  Asus has instructions  on their website to reset the EC by holding down the power button for a bit, but that didn't  work for me.  I'm hoping the next bios update will fix it. Would love to know if anyone gets the WMI functions working. I no longer have windows installed.

My setup, that is getting more stable by the day:
     - PopOS 24.10 alpha, gnome wayland desktop (COSMIC crashes on startup, but not always.. gnome seems very stable)
     - linux-next git updated whenever I see a merge that might be related (currently running 202140821). Added BT ID's manually.
     - MESA and libdri latest stable releases from kisak PPA.  Seems much more stable than mesa-git builds.
     - PSR disabled on cmdline, I do get occasional GPU pauses that resume after 10s or so.  

Thank you so much for posting the speaker config, that one was really confounding me and it works fine now with your pipewire config.

**Comment by frogmech** [comment]
Here's the fix for keyboard backlight control:
```
# Run as root
cd /sys/kernel/debug/asus-nb-wmi
echo 0x5002f > dev_id
echo 1 > ctrl_param
cat devs
```

I found it from [this post](https://bbs.archlinux.org/viewtopic.php?id=298591) on the Arch forum. It seems to keep working for me even after a restart without creating a systemd service even though the people on the forum post say it is necessary. I guess ASUS laptops have an OOBE that I assume is marked as complete when you go through the Windows setup. I wonder if the only ones affected by this bug are people that skipped the Windows setup and went straight to installing Linux?

**Comment by fallingcats** [comment]
> Here's the fix for keyboard backlight control:
> 
> ```
> # Run as root
> cd /sys/kernel/debug/asus-nb-wmi
> echo 0x5002f > dev_id
> echo 1 > ctrl_param
> cat devs
> ```
> 
> I found it from [this post](https://bbs.archlinux.org/viewtopic.php?id=298591) on the Arch forum. It seems to keep working for me even after a restart without creating a systemd service even though the people on the forum post say it is necessary. I guess ASUS laptops have an OOBE that I assume is marked as complete when you go through the Windows setup. I wonder if the only ones affected by this bug are people that skipped the Windows setup and went straight to installing Linux?

Thank you so, so much for also posting this here.

For the record, I set up windows, did firmware updates, and then swapped in the 4TB drive with my arch install. Yet I was affected.

**Comment by skbolton** [comment]
> Thank you so, so much for also posting this here.
> 
> For the record, I set up windows, did firmware updates, and then swapped in the 4TB drive with my arch install. Yet I was affected.

Yeah absolutely @fallingcats @frogmech super stoked to have this issue resolved! Now if somehow we could get deep sleep as a suspend option I would have 0 regrets with this laptop. One step closer!

**Comment by ThatOneCalculator** [comment]
> I wonder if the only ones affected by this bug are people that skipped the Windows setup and went straight to installing Linux?

Maybe... that's what I did. Hopefully it can get into kernel patch form soon so I can add it to my AUR kernel package lol

**Comment by skbolton** [comment]
I also have the issue of rebooting wiping things. But my setup is all in nixos so I think I am going to go through the windows installation and then reinstall nixos. Will report back if that is a valid solution

**Comment by BNieuwenhuizen** [comment]
> Here's the fix for keyboard backlight control:
> 
> ```
> # Run as root
> cd /sys/kernel/debug/asus-nb-wmi
> echo 0x5002f > dev_id
> echo 1 > ctrl_param
> cat devs
> ```
> 
> I found it from [this post](https://bbs.archlinux.org/viewtopic.php?id=298591) on the Arch forum. It seems to keep working for me even after a restart without creating a systemd service even though the people on the forum post say it is necessary. I guess ASUS laptops have an OOBE that I assume is marked as complete when you go through the Windows setup. I wonder if the only ones affected by this bug are people that skipped the Windows setup and went straight to installing Linux?

FWIW it works for me  by default if I reboot from Windows into Linux but not with a cold boot.

Anyway, converted this into a kernel patch: https://patchwork.kernel.org/project/platform-driver-x86/patch/20240909223503.1445779-1-bas@basnieuwenhuizen.nl/

so hopefully this works OOB (pun intended) in some future kernel version.

**Comment by clemej** [comment]
Thanks, works for me as well!  I often work late into the night in a dark room and it was getting very distracting for both myself and those around me.

**Comment by skbolton** [comment]
Just wanted to report that building linux kernel 6.11 on nixos included this patch.

**Comment by LC43** [comment]
also, using `brightnessctl -d 'asus::kbd_backlight' set x` , where x is 0 to 3, controls the keyboard light for me

**Comment by skbolton** [comment]
> also, using `brightnessctl -d 'asus::kbd_backlight' set x` , where x is 0 to 3, controls the keyboard light for me

@LC43 what Kernel are you on? I think that command only works with the correct kernel.

**Comment by LC43** [comment]
> > also, using `brightnessctl -d 'asus::kbd_backlight' set x` , where x is 0 to 3, controls the keyboard light for me
> 
> @LC43 what Kernel are you on? I think that command only works with the correct kernel.

`6.11.0-8-generic #8-Ubuntu SMP PREEMPT_DYNAMIC`

works well for me on 6.11 :)

**Comment by skbolton** [comment]
> works well for me on 6.11 :)

Right just wanted to clarify because I tried that command too and it didn't work before. Seems that kernel >=6.11 is what makes things work.

**Comment by LC43** [comment]
thanks, it helps others knowing that, for those who come for this issue!

**Comment by ThatOneCalculator** [comment]
This issue should be closed now

**Comment by clemej** [comment]
Can.. I close this? Lemme check.

**Comment by litemotiv** [comment]
Hi guys, i noticed that the keyboard backlight seems a lot brighter than on windows, even on the lowest step it's still quite bright. Does anyone know how we could make this more granular, and perhaps get it into the kernel upstream?
