### ISSUE TITLE
PSR issues even with linux-mainline-um5606 and linux-firmware-amd-staging-um5606-git

### ISSUE THREAD

**Issue by frogmech** [BNieuwenhuizen/zenbook-s16#7]
According to the [UM5606 Arch Wiki page](https://wiki.archlinux.org/title/ASUS_Zenbook_UM5606), disabling PSR is unnecessary if you use linux-mainline-um5606 and linux-firmware-amd-staging-um5606-git. It doesn't seem to freeze/hang anymore with PSR enabled; however, I get terrible performance, especially when playing videos. Does anyone else have this issue? Is there a solution for this or should I just keep PSR disabled for now?

**Comment by ThatOneCalculator** [comment]
Unfortunately I'm unable to reproduce your issue :(

As this has to do with the Wiki page, maybe put it on the talk section?

**Comment by frogmech** [comment]
I'll post it there too, I just figured I'd get better (and quicker) answers here.

**Comment by ThatOneCalculator** [comment]
Fwiw I'm the author of the wiki page too

**Comment by fallingcats** [comment]
I think I might know what you're talking about? I've noticed kwin sometimes drops from 120Hz to around 52 when doing mundane things like opening an Applet in the tray or scrolling a webpage. Except it doesn't just drop a few frames, it consistently stays at those  (reportedly) 52fps for longer periods (but It honestly feels even much worse than that, like half).

**Comment by fallingcats** [comment]
Okay, in my case kwin had issues with the dynamic triple buffering they introduced last year.
I needed to disable it by having kwin start the right env set:

To edit the service unit: `systemctl edit --user plasma-kwin_wayland.service`

And add this (`~/.config/systemd/user/plasma-kwin_wayland.service.d/override.conf`):
```
[Service]
Environment="KWIN_DRM_DISABLE_TRIPLE_BUFFERING=1"
```

Feel free to add that to the wiki, I don't have an account.

**Comment by ThatOneCalculator** [comment]
Since I don't have KDE installed, does `systemctl edit --user plasma-kwin_wayland.service` take you right into editing the file?

**Comment by ThatOneCalculator** [comment]
Looks good?

![image](https://github.com/user-attachments/assets/3de30277-8a34-4bac-b8ca-452d94efbb26)

**Comment by fallingcats** [comment]
Yes it does. If you use the edit command you don't need to `systemctl daemon-reload --user` later, and you also don't need to create the directory structure for the drop-in config file

**Comment by ThatOneCalculator** [comment]
Added to the wiki!

**Comment by fallingcats** [comment]
Thanks :)

**Comment by frogmech** [comment]
Thank you, this seems to have fixed the issue. It's really strange because I don't recall having this problem before I found out I needed to disable PSR when I first got the laptop.
